In [1]:
import pandas as pd
from Bio import Entrez
Entrez.email = 'dmalzl@cemm.oeaw.ac.at'
Entrez.api_key = '746c80043a6e2ceeb01ae587f8ab1a8ace09'


srauid_map = pd.read_csv(
    'metadata/archs4_accession_to_uid.tsv.gz',
    sep = '\t',
    compression = 'gzip'
)

# may contain duplicates
srauid_map.drop_duplicates(inplace = True)
srauid_map

        accession     uid database
0       SRX185895  243394      sra
1       SRX185896  243395      sra
2       SRX185897  243396      sra
3       SRX185898  243397      sra
4       SRX185899  243398      sra
...           ...     ...      ...
722660  SRX185248  242745      sra
722661  SRX185249  242746      sra
722662  SRX185250  242747      sra
722663  SRX185251  242748      sra
722664  SRX185252  242749      sra

[722425 rows x 3 columns]

In [ ]:
from metadatamapping import metadata

accessions = metadata.srauids_to_accessions(srauid_map)

MainThread: 2023-11-21 15:36:16-INFO-retrieving uids 0 to 50000
MainThread: 2023-11-21 15:38:08-INFO-retrieving uids 50000 to 100000
MainThread: 2023-11-21 15:40:05-INFO-retrieving uids 100000 to 150000
MainThread: 2023-11-21 15:41:57-INFO-retrieving uids 150000 to 200000
MainThread: 2023-11-21 15:44:06-INFO-retrieving uids 200000 to 250000
MainThread: 2023-11-21 15:46:25-INFO-retrieving uids 250000 to 300000
MainThread: 2023-11-21 15:48:30-INFO-retrieving uids 300000 to 350000
MainThread: 2023-11-21 15:50:36-INFO-retrieving uids 350000 to 400000
MainThread: 2023-11-21 15:52:56-INFO-retrieving uids 400000 to 450000
MainThread: 2023-11-21 15:55:51-INFO-retrieving uids 450000 to 500000
MainThread: 2023-11-21 15:58:16-INFO-retrieving uids 500000 to 550000
MainThread: 2023-11-21 16:01:16-INFO-retrieving uids 550000 to 600000
MainThread: 2023-11-21 16:04:01-INFO-retrieving uids 600000 to 650000

In [ ]:
from metadatamapping import link
linked_uids = link.link_sra_to_biosample(srauid_map.uid)
linked_uids

In [36]:
linked_uids.to_csv(
    'sra_to_biosample.csv',
    index = False
)

In [14]:
import numpy as np


linked_uids = pd.read_csv(
    'sra_to_biosample.csv.gz',
    compression = 'gzip'
)
linked_uids = linked_uids.dropna()
linked_uids['biosample'] = linked_uids.biosample.astype(int)
linked_uids

           sra  biosample
0       243394    1163911
1       243395    1163912
2       243396    1163913
3       243397    1163914
4       243398    1163915
...        ...        ...
722428  242745    1163627
722429  242746    1163628
722430  242747    1163629
722431  242748    1163630
722432  242749    1163631

[722243 rows x 2 columns]

In [17]:
biosample_metadata = metadata.biosample_uids_to_metadata(linked_uids.biosample)

retrieving uids 0 to 50000
{'QueryKey': '1', 'WebEnv': 'MCID_655714994ac1f824cd3d17b4'}
retrieving uids 100000 to 150000
{'QueryKey': '1', 'WebEnv': 'MCID_655715d022cf3030690be185'}
retrieving uids 150000 to 200000
{'QueryKey': '1', 'WebEnv': 'MCID_6557166cb4cc234ff22a2b75'}
retrieving uids 200000 to 250000
{'QueryKey': '1', 'WebEnv': 'MCID_655716ddb4cc234ff22a2ce6'}
retrieving uids 250000 to 300000
{'QueryKey': '1', 'WebEnv': 'MCID_655717525e9c76586032b298'}
retrieving uids 300000 to 350000
{'QueryKey': '1', 'WebEnv': 'MCID_655717b0b4cc234ff22a2f4c'}
retrieving uids 350000 to 400000
{'QueryKey': '1', 'WebEnv': 'MCID_65571813c93597127f343df2'}
retrieving uids 400000 to 450000
{'QueryKey': '1', 'WebEnv': 'MCID_65571874b4cc234ff22a31b0'}
retrieving uids 450000 to 500000
{'QueryKey': '1', 'WebEnv': 'MCID_655718dab4cc234ff22a3314'}
retrieving uids 500000 to 550000
{'QueryKey': '1', 'WebEnv': 'MCID_6557193ca21ef36d661657f2'}
retrieving uids 550000 to 600000
{'QueryKey': '1', 'WebEnv': 'MCID_655719a126d75b4c584c570c'}
retrieving uids 600000 to 650000
{'QueryKey': '1', 'WebEnv': 'MCID_65571a04b4cc234ff22a37b0'}
retrieving uids 650000 to 700000
{'QueryKey': '1', 'WebEnv': 'MCID_65571a635e9c76586032b814'}
retrieving uids 700000 to 722243
{'QueryKey': '1', 'WebEnv': 'MCID_65571ac8c93597127f34434e'}

In [18]:
metadata.to_csv('biosample_metadata.csv', index = False)

In [19]:
metadata

,title,attribute,organism,biosample
0,OCI-LY1_48hrs_mRNAseq_3x_siNT_R1,source_name: Human DLBCL cel line; treatment: ...,Homo sapiens;9606,1163911
1,OCI-LY1_48hrs_mRNAseq_3x_siNT_R2,source_name: Human DLBCL cel line; treatment: ...,Homo sapiens;9606,1163912
2,OCI-LY1_48hrs_mRNAseq_3x_siNT_R3,source_name: Human DLBCL cel line; treatment: ...,Homo sapiens;9606,1163913
3,OCI-LY1_48hrs_mRNAseq_3x_siBCL6_R1,source_name: Human DLBCL cel line; treatment: ...,Homo sapiens;9606,1163914
4,OCI-LY1_48hrs_mRNAseq_3x_siBCL6_R2,source_name: Human DLBCL cel line; treatment: ...,Homo sapiens;9606,1163915
...,...,...,...,...
22217,Parkinson's Disease PD 13,source_name: Brain cortex; tissue: Human brain...,Homo sapiens;9606,1163627
22218,Parkinson's Disease PD 14,source_name: Brain cortex; tissue: Human brain...,Homo sapiens;9606,1163628
22219,Parkinson's Disease PD 15,source_name: Brain cortex; tissue: Human brain...,Homo sapiens;9606,1163629
22220,Parkinson's Disease PD 16,source_name: Brain cortex; tissue: Human brain...,Homo sapiens;9606,1163630
22221,Parkinson's Disease PD 17,source_name: Brain cortex; tissue: Human brain...,Homo sapiens;9606,1163631

In [21]:
import certifi
import urllib3
from io import BytesIO


study_ids = merged.study.unique()
metasra_data = []
urllib3.disable_warnings()
print(f'retrieving {len(study_ids)} studies')
for i, study_id in enumerate(study_ids):
    # cert_reqs = 'CERT_NONE' not recommended but needed due to unresolvable SSLError
    http = urllib3.PoolManager(
        ca_certs = certifi.where(),
        cert_reqs = 'CERT_NONE'                      
    )

    # retrieving number of studies that match search criteria
    r = http.request(
        'GET', 
        'http://metasra.biostat.wisc.edu/api/v01/samples.csv',
        fields = {
            'study': study_id,
            'species': 'human', 
            'assay': 'RNA-seq', 
            'limit': 10000,
            'skip': 0
        }
    )
    if not i + 1 % 1000:
        print(i)

    study_data = pd.read_csv(BytesIO(r.data))
    metasra_data.append(study_data)

metasra = pd.concat(metasra_data)

retrieving 20217 studies
1
1001
2001
3001
4001
5001
6001
7001
8001
9001
10001
11001
12001
13001
14001
15001
16001
17001
18001
19001
20001

/tmp/ipykernel_57092/74238611.py:35: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  metasra = pd.concat(metasra_data)

In [22]:
metasra = pd.concat(metasra_data)
metasra

/tmp/ipykernel_57092/1472980570.py:1: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  metasra = pd.concat(metasra_data)

,study_id,study_title,sample_id,sample_name,sample_type,sample_type_confidence,mapped_ontology_ids,mapped_ontology_terms,raw_SRA_metadata,sample_species,assay
0,SRP031885,Brd4 and JMJD6-associated Anti-pause Enhancers...,SRS1369056,HEK293T cell,cell line,1.000000,"CL:0000010, CVCL:0045, EFO:0001182, EFO:000072...","cultured cell, HEK293, transfection, kidney",cell line: Human Embryonic Kidney 293 cells; s...,human,RNA-seq
1,SRP031885,Brd4 and JMJD6-associated Anti-pause Enhancers...,SRS1369051,HEK293T cell,cell line,1.000000,"CL:0000010, CVCL:0045, EFO:0001182, EFO:000072...","cultured cell, HEK293, transfection, kidney",cell line: Human Embryonic Kidney 293 cells; s...,human,RNA-seq
2,SRP031885,Brd4 and JMJD6-associated Anti-pause Enhancers...,SRS1369055,HEK293T cell,cell line,1.000000,"CL:0000010, CVCL:0045, EFO:0001182, EFO:000072...","cultured cell, HEK293, transfection, kidney",cell line: Human Embryonic Kidney 293 cells; s...,human,RNA-seq
3,SRP031885,Brd4 and JMJD6-associated Anti-pause Enhancers...,SRS1369050,HEK293T cell,cell line,1.000000,"CL:0000010, CVCL:0045, EFO:0001182, EFO:000072...","cultured cell, HEK293, transfection, kidney",cell line: Human Embryonic Kidney 293 cells; s...,human,RNA-seq
4,SRP031885,Brd4 and JMJD6-associated Anti-pause Enhancers...,SRS1369059,HEK293T cell,cell line,1.000000,"CL:0000010, CVCL:0045, EFO:0001182, EFO:000072...","cultured cell, HEK293, transfection, kidney",cell line: Human Embryonic Kidney 293 cells; s...,human,RNA-seq
...,...,...,...,...,...,...,...,...,...,...,...
28,SRP015668,aSyn polyA-RNAseq in PD and unaffected cortica...,SRS361730,Brain cortex,tissue,0.945379,"DOID:14330, EFO:0002508, EFO:0003534, UBERON:0...","Parkinson's disease, dorsal telencephalon, mal...",disease state: Parkinson's Disease PD; gender:...,human,RNA-seq
29,SRP015668,aSyn polyA-RNAseq in PD and unaffected cortica...,SRS361740,Brain cortex,tissue,0.945379,"DOID:14330, EFO:0002508, EFO:0003534, UBERON:0...","Parkinson's disease, dorsal telencephalon, mal...",disease state: Parkinson's Disease PD; gender:...,human,RNA-seq
30,SRP015668,aSyn polyA-RNAseq in PD and unaffected cortica...,SRS361739,Brain cortex,tissue,0.945379,"DOID:14330, EFO:0002508, EFO:0003534, UBERON:0...","Parkinson's disease, dorsal telencephalon, mal...",disease state: Parkinson's Disease PD; gender:...,human,RNA-seq
31,SRP015668,aSyn polyA-RNAseq in PD and unaffected cortica...,SRS361732,Brain cortex,tissue,0.945379,"DOID:14330, EFO:0002508, EFO:0003534, UBERON:0...","Parkinson's disease, dorsal telencephalon, mal...",disease state: Parkinson's Disease PD; gender:...,human,RNA-seq
32,SRP015668,aSyn polyA-RNAseq in PD and unaffected cortica...,SRS361737,Brain cortex,tissue,0.945379,"DOID:14330, EFO:0002508, EFO:0003534, UBERON:0...","Parkinson's disease, dorsal telencephalon, mal...",disease state: Parkinson's Disease PD; gender:...,human,RNA-seq

In [23]:
metasra.to_csv(
    'metasra_metadata.csv',
    index = False
)